//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Info
    {
        public User_Info()
        {
            this.UserRole = new HashSet<UserRole>();
        }
        
        public int UserID { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType("Password")]
        public string Password { get; set; }
        [Required]
        [DataType("Password")]
        public string ConfirmPassword { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
